title: Micah Chang
description: Micah Chang personal blog
theme: just-the-docs

url: https://micahc03.github.io/blog

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
